function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 24-Feb-2021 06:03:09

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.123725694506998 0.101785714285714 0.740857638826335 0.823214285714285]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',4);

% Create ylabel
ylabel('State');

% Create xlabel
xlabel('Time, seconds');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',14,'GridAlpha',0.3,'GridColor',...
    [0.349019607843137 0.349019607843137 0.349019607843137],'MinorGridColor',...
    [0.2 0.2 0.2],'XGrid','on','XMinorGrid','on','YGrid','on');
