function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  stairs x
%  Y1:  stairs y

%  Auto-generated by MATLAB on 24-Feb-2021 06:00:09

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.123725694506998 0.101785714285714 0.740857638826335 0.823214285714285]);
hold(axes1,'on');

% Create stairs
stairs(X1,Y1,'LineWidth',4);

% Create ylabel
ylabel('Signal','FontSize',14);

% Create xlabel
xlabel('Time, seconds','FontSize',14);

box(axes1,'on');
hold(axes1,'off');
