function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 24-Feb-2021 05:52:10

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.123725694506998 0.101785714285714 0.740857638826335 0.823214285714285]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',4,'Parent',axes1);
set(plot1(1),'DisplayName','Start');
set(plot1(2),'DisplayName','Stop','LineStyle','--');
set(plot1(3),'DisplayName','Reverse');
set(plot1(4),'DisplayName','Rele','LineStyle',':');

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1(1),1,1);
% Create datatip
datatip(plot1(1),'DataIndex',4);

% Create ylabel
ylabel('Signal');

% Create xlabel
xlabel('Time,seconds');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 30]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 2]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',15);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',14);

