function createfigure(X1, Y1, Y2, Y3)
%CREATEFIGURE(X1, Y1, Y2, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 24-Feb-2021 01:23:37

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.213405797101449 0.815]);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',2,'Color',[0 0 0]);

% Create ylabel
ylabel('Angle, radians','Interpreter','latex');

% Create xlabel
xlabel('Time, seconds','Interpreter','latex');

% Create title
title('Rotation');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',14,'XColor',[0 0 0],'XGrid','on','YColor',[0 0 0],...
    'YGrid','on','ZColor',[0 0 0]);
% Create subplot
subplot1 = subplot(1,3,2,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y2,'Parent',subplot1,'LineWidth',2,'Color',[0 0 0]);

% Create ylabel
ylabel('Velocity, radians per seconds','Interpreter','latex');

% Create xlabel
xlabel('Time, seconds','Interpreter','latex');

% Create title
title('Velocity');

box(subplot1,'on');
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'FontSize',14,'XGrid','on','YGrid','on');
% Create subplot
subplot2 = subplot(1,3,3,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X1,Y3,'Parent',subplot2,'LineWidth',2,'Color',[0 0 0]);

% Create ylabel
ylabel('Acceleration, radians per seconds^2');

% Create xlabel
xlabel('Time, seconds','Interpreter','latex');

% Create title
title('Acceleration');

box(subplot2,'on');
hold(subplot2,'off');
% Set the remaining axes properties
set(subplot2,'FontSize',14,'XGrid','on','YGrid','on');
