function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 23-Feb-2021 23:32:05

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',6,'Parent',axes1);
set(plot1(1),'DisplayName','Model 1','LineWidth',3);
set(plot1(2),'DisplayName','Model 2','LineStyle','--');
set(plot1(3),'DisplayName','Model 3','LineStyle',':');

% Create ylabel
ylabel('Phi, degrees','FontSize',16,'Interpreter','latex');

% Create xlabel
xlabel('Time, seconds','FontSize',14,'Interpreter','latex');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast','FontSize',14);

